"""update user grant relationships

Revision ID: cbb08aabc4d3
Revises: 1516623ae03e
Create Date: 2026-07-02 15:54:08.540554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb08aabc4d3'
down_revision: Union[str, Sequence[str], None] = '1516623ae03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.add_column('grants', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grants', 'expires_at')
    op.drop_column('grants', 'revoked')
    # ### end Alembic commands ###
